name: Notify Splunk on Commit

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub commit event to Splunk Observability
        run: |
          curl -X POST https://api.us1.signalfx.com/v2/event \
          -H "X-SF-TOKEN: mOmfiUegLcEESZDHjYpzow" \
          -H "Content-Type: application/json" \
          -d '{
                "eventType": "github.commit",
                "category": "USER_DEFINED",
                "dimensions": {
                  "repository": "${{ github.repository }}",
                  "pusher": "${{ github.actor }}"
                },
                "properties": {
                  "message": "Commit pushed to GitHub",
                  "commit_sha": "${{ github.sha }}"
                }
              }'
 