name: Notify Splunk on Commit

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send log to Splunk
        run: |
          curl -k https://us0.splunkcloud.com:8088/services/collector \
          -H "Authorization: Splunk <your-token>" \
          -H "Content-Type: application/json" \
          -d '{"event": "GitHub commit pushed", "sourcetype": "github", "source": "demo-dora"}'
 