name: Report Commit to Splunk Observability

on:
  push:
    branches:
      - main

jobs:
  report-to-splunk:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Splunk Observability
        run: |
          curl -X POST "https://api.us1.signalfx.com/v2/event" \
            -H "Content-Type: application/json" \
            -H "X-SF-TOKEN: ${{ secrets.SPLUNK_TOKEN }}" \
            -d '{
              "eventType": "github.commit",
              "dimensions": {
                "repo": "${{ github.repository }}",
                "branch": "${{ github.ref_name }}"
              },
              "properties": {
                "commit_sha": "${{ github.sha }}",
                "author": "${{ github.actor }}",
                "message": "${{ github.event.head_commit.message }}"
              }
            }'
