
# .github/workflows/splunk-events.yml
name: Send GitHub Events to Splunk
on:
  push:
  pull_request:
  deployment:
  deployment_status:

jobs:
  send-to-splunk:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub event to Splunk HEC
        env:
          HEC_URL: ${{ secrets.SPLUNK_HEC_URL }}   
          HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}
        run: |
          curl -sS -X POST "$HEC_URL" \
               -H "Authorization: Splunk $HEC_TOKEN" \
               -H "Content-Type: application/json" \
               --data-binary @${GITHUB_EVENT_PATH} \
               -k
